name: VizElfs
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bottleneck=1.4.2=py311h03d0aa3_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.30=hf2bb037_2
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - ncurses=6.5=hee39554_0
  - numexpr=2.14.1=py311h5fbe615_0
  - numpy=2.3.4=py311h4bb6f22_1
  - numpy-base=2.3.4=py311h23175f9_1
  - openssl=3.0.18=h9b4081a_0
  - pandas=2.3.3=py311h3f644e9_1
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py311hca03da5_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
prefix: /Users/aurafrizzati/anaconda3/envs/VizElfs
